### ISSUE TITLE
A few bugs

### ISSUE THREAD

**Issue by grandamp** [grandamp/rest-service#447]
- `validationPolicyId` is no longer an OID (service issue)
- Python example `validate.py` *should* handle the exception (client issue)

```TEXT
$ curl -v https://www.idmanagement.gov/implement/tools/CACertificatesValidatingToFederalCommonPolicyG2.p7b --output /tmp/ACertificatesValidatingToFederalCommonPolicyG2.p7b

$ ./validate.py /tmp/CACertificatesValidatingToFederalCommonPolicyG2.p7b https://api.keysupport.org foo

Request:
{
    "validationPolicyId": "foo",
    "x509Certificate": "MIIEjzCCA3egAwIBAgICAwMwDQYJKoZIhvcNAQELBQAwWzELMAkGA1UEBhMCVVMxGDAWBgNVBAoTD1UuUy4gR292ZXJubWVudDEMMAoGA1UECxMDRG9EMQwwCgYDVQQLEwNQS0kxFjAUBgNVBAMTDURvRCBSb290IENBIDMwHhcNMTkwNDAyMTMzNDQ5WhcNMjUwNDAyMTMzNDQ5WjBaMQswCQYDVQQGEwJVUzEYMBYGA1UEChMPVS5TLiBHb3Zlcm5tZW50MQwwCgYDVQQLEwNEb0QxDDAKBgNVBAsTA1BLSTEVMBMGA1UEAxMMRE9EIFNXIENBLTYwMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA/MzAiiVCG61CNrHuJ+6kXRAlG9ppLKXje1S3mw0LXOynYAyX7OIyFXkeNj54DV/4HTvK4eHdG8XTfiUr8cqWki2nHPJivaZOKu/jObshywNZ3UAKmtz8bPDO+wJ8QrAxKaQYH4CMmHlEjetmM7CMRznfMDqjwB9us5Y1FwKPlh+2Y6rdDfU1xR/dGD2iQk4laduxCCr4ULI7eFFToxnr5rUt95FBi5DlIPs3XETIywIWJ7Z59m0JBrReqKnFZr1NR06DGCOOYULORCXiZFJlbRMjwvd3BPu+auP39/qq6aKLmTy0iTPflGum94W4bkvupB3r6VkbptNsZrFq0IYZkQIDAQABo4IBXDCCAVgwHwYDVR0jBBgwFoAUbIqUonexgHIdgXoWqvLczmbuRcAwHQYDVR0OBBYEFH3+8BAXOb/TcoT9rSlw+OI9mfMYMA4GA1UdDwEB/wQEAwIBhjA9BgNVHSAENjA0MAsGCWCGSAFlAgELJDALBglghkgBZQIBCycwCwYJYIZIAWUCAQsqMAsGCWCGSAFlAgELOzASBgNVHRMBAf8ECDAGAQH/AgEAMAwGA1UdJAQFMAOAAQAwNwYDVR0fBDAwLjAsoCqgKIYmaHR0cDovL2NybC5kaXNhLm1pbC9jcmwvRE9EUk9PVENBMy5jcmwwbAYIKwYBBQUHAQEEYDBeMDoGCCsGAQUFBzAChi5odHRwOi8vY3JsLmRpc2EubWlsL2lzc3VlZHRvL0RPRFJPT1RDQTNfSVQucDdjMCAGCCsGAQUFBzABhhRodHRwOi8vb2NzcC5kaXNhLm1pbDANBgkqhkiG9w0BAQsFAAOCAQEAn4OSx5FWM4e2vd2Igv63CCpfvrQqv5bjuoyQhoIJbEpjx6xtof1SNSwtPDjDtSawzhabKYTgSajw28zIyJ4TpFUiABOSNkA4aYWvtjjHPKPrIjVTck0DArWH2Lr9x0dvpCIInDyfIib9dcE0cdGVlEpeAEMQFjpUbmCNpTlKUtSroY8CfZCOmi+Rp/fT0N9PoO/Izxl1UvHb9xxfu4vasVjt3L/Fu8PIw8GJ70u/Ws+mg3ga8uDOluYn+VDqO1Le2QJvSK0J9dS21rwV6SCtf+en2Razi0/S44tzOFa4fRdJLHTYPutu69p6+YMhSul++7G14BLwhmWa2iRcjw+AlQ=="
}

Response:
{
    "status": "BAD_REQUEST",
    "message": "validationPolicyId must be an Object Identifier"
}
Traceback (most recent call last):
  File "/home/tejohnson/eclipse-workspace/rest-service/client/python/./validate.py", line 74, in <module>
    validateCert(certificate)
  File "/home/tejohnson/eclipse-workspace/rest-service/client/python/./validate.py", line 47, in validateCert
    x509IssuerName = resJson["x509IssuerName"]
KeyError: 'x509IssuerName'
```

**Comment by grandamp** [comment]
- Using IAL3 policy:

```TEXT
$ ./validate.py /tmp/CACertificatesValidatingToFederalCommonPolicyG2.p7b http://localhost:5000 cc54e0ec-49da-333a-8150-2dd00b758b17 > /tmp/ial3.pem
$ openssl crl2pkcs7 -outform DER -out /tmp/ial3.p7b -nocrl -certfile /tmp/ial3.pem 
$ cp /tmp/ial3.pem /tmp/ial3.log
 openssl pkcs7 -inform DER -in /tmp/ial3.p7b -print_certs > /tmp/ial3_pem.log
```

[ial3.log](https://github.com/grandamp/rest-service/files/12826272/ial3.log)
[ial3_pem.log](https://github.com/grandamp/rest-service/files/12826284/ial3_pem.log)

**Comment by grandamp** [comment]
Closing issue since it was based on a very old version of the rest service, and OIDs were re-introduced for certificate validation policies.
